In [61]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
data = pd.read_csv('Clean_AirbnbData.csv')

In [62]:
data.drop(data[(data['price'] >1700)].index,inplace=True)

In [63]:
data

,host_response_time,host_response_rate,host_acceptance_rate,host_is_superhost,host_total_listings_count,host_has_profile_pic,host_identity_verified,neighbourhood_cleansed,latitude,longitude,...,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,reviews_per_month,amenities_count,host_experience_days
0,within a few hours,1.00,0.69,True,2.0,True,True,Dovercourt-Wallace Emerson-Junction,43.664340,-79.424960,...,4.96,4.91,4.94,4.89,4.89,4.77,False,0.95,31,1371.0
1,no response,0.00,0.00,False,1.0,True,True,Waterfront Communities-The Island,43.646980,-79.391210,...,5.00,5.00,5.00,5.00,5.00,5.00,False,0.04,16,2151.0
2,no response,0.00,0.00,False,1.0,True,False,Playter Estates-Danforth,43.679430,-79.348530,...,5.00,5.00,5.00,5.00,5.00,4.75,False,0.08,12,2971.0
3,no response,0.00,0.00,False,4.0,True,True,High Park North,43.659530,-79.454160,...,4.38,4.63,4.50,4.88,5.00,4.75,True,0.19,22,3509.0
5,within an hour,0.94,0.98,True,3.0,True,True,The Beaches,43.666800,-79.303470,...,5.00,4.88,5.00,5.00,5.00,5.00,False,0.16,62,1245.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12491,within an hour,1.00,0.98,True,2.0,True,True,Newtonbrook East,43.800050,-79.414380,...,4.97,5.00,4.97,5.00,4.87,4.97,False,0.70,33,3038.0
12492,within an hour,1.00,0.90,False,4.0,True,True,Milliken,43.845380,-79.287840,...,4.82,4.45,4.82,4.55,4.73,4.82,False,1.07,30,3948.0
12493,within an hour,1.00,0.90,False,4.0,True,True,Milliken,43.846867,-79.286163,...,4.68,4.44,4.64,4.44,4.08,4.36,False,0.63,29,3948.0
12494,within an hour,1.00,0.90,False,4.0,True,True,Milliken,43.846990,-79.287690,...,4.65,4.65,4.87,4.74,4.48,4.74,False,1.62,30,3948.0
12495,within an hour,1.00,1.00,True,1.0,True,True,Newtonbrook East,43.809400,-79.421300,...,4.85,5.00,4.92,4.85,4.54,4.77,False,1.54,60,4119.0

In [64]:
X = data.iloc[:,[1,2,4,5,6,12,13,14,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35]].values
X
Y = data["price"]
Y

0         90.0
1        130.0
2         45.0
3         80.0
5        359.0
         ...
12491     61.0
12492     51.0
12493     51.0
12494     51.0
12495    240.0
Name: price, Length: 12447, dtype: float64

In [65]:

Y_train, Y_test, X_train, X_test = train_test_split(Y,X,test_size = 0.2, random_state = 100)

from sklearn import linear_model

LINREG = linear_model.LinearRegression()
LINREG.fit(X_train,Y_train)
LINREG.score(X_test,Y_test)

0.4368166994167416

In [66]:
Y_pred= LINREG.predict(X_test)
Y_pred

array([144.10607373, 630.93099727, 426.6956946 , ..., 191.80334968,
       427.08902098, 143.96002379])

In [67]:
Accuracy= r2_score(Y_test,Y_pred)*100
print(" Accuracy of the model is %.2f" %Accuracy)

 Accuracy of the model is 43.68